import type { Product, ProductCategory } from "@/lib/types";

export const catalogCategories: ProductCategory[] = [
  "Hot Coffee",
  "Iced Coffee",
  "Bakery",
  "Dessert",
];

export const catalog: Product[] = [
  {
    id: "signature-latte",
    name: "Signature Latte",
    detail: "Double espresso, steamed milk, rosetta art",
    category: "Hot Coffee",
    priceCents: 52000,
    image: "/menu/signature-latte.jpg",
    imageAlt: "A hot latte in a ceramic cup with latte art",
    tags: ["latte", "espresso", "milk"],
    popular: true,
  },
  {
    id: "salted-caramel-cappuccino",
    name: "Salted Caramel Cappuccino",
    detail: "Espresso, microfoam, caramel drizzle",
    category: "Hot Coffee",
    priceCents: 58000,
    image: "/menu/salted-caramel-cappuccino.jpg",
    imageAlt: "A caramel cappuccino in a ceramic cup",
    tags: ["cappuccino", "caramel", "espresso"],
    popular: true,
  },
  {
    id: "vanilla-oat-flat-white",
    name: "Vanilla Oat Flat White",
    detail: "Oat milk, vanilla, ristretto espresso",
    category: "Hot Coffee",
    priceCents: 59000,
    image: "/menu/vanilla-oat-flat-white.jpg",
    imageAlt: "A flat white in a small ceramic cup",
    tags: ["flat white", "oat", "vanilla"],
  },
  {
    id: "dark-mocha",
    name: "Dark Mocha",
    detail: "Dark chocolate, espresso, whipped cream",
    category: "Hot Coffee",
    priceCents: 62000,
    image: "/menu/dark-mocha.jpg",
    imageAlt: "A dark mocha with whipped cream in a ceramic mug",
    tags: ["mocha", "chocolate", "espresso"],
  },
  {
    id: "vietnamese-phin-iced-coffee",
    name: "Vietnamese Phin Iced Coffee",
    detail: "Robusta, condensed milk, hand-shaken ice",
    category: "Iced Coffee",
    priceCents: 49000,
    image: "/menu/vietnamese-phin-iced-coffee.jpg",
    imageAlt: "A glass of iced Vietnamese coffee with condensed milk",
    tags: ["phin", "iced", "condensed milk"],
    popular: true,
  },
  {
    id: "coconut-cold-brew",
    name: "Coconut Cold Brew",
    detail: "Cold brew, coconut cream, crystal ice",
    category: "Iced Coffee",
    priceCents: 64000,
    image: "/menu/coconut-cold-brew.jpg",
    imageAlt: "A glass of coconut cold brew with foam",
    tags: ["cold brew", "coconut", "iced"],
  },
  {
    id: "espresso-tonic",
    name: "Espresso Tonic",
    detail: "Sparkling tonic, espresso float, citrus oil",
    category: "Iced Coffee",
    priceCents: 61000,
    image: "/menu/espresso-tonic.jpg",
    imageAlt: "A tall glass of espresso tonic with ice",
    tags: ["tonic", "sparkling", "espresso"],
  },
  {
    id: "matcha-cream-latte",
    name: "Matcha Cream Latte",
    detail: "Ceremonial matcha, milk, cream cap",
    category: "Iced Coffee",
    priceCents: 65000,
    image: "/menu/matcha-cream-latte.jpg",
    imageAlt: "A glass of iced matcha latte with cream",
    tags: ["matcha", "cream", "iced"],
  },
  {
    id: "almond-croissant",
    name: "Almond Croissant",
    detail: "Butter croissant, almond cream, toasted flakes",
    category: "Bakery",
    priceCents: 55000,
    image: "/menu/almond-croissant.jpg",
    imageAlt: "An almond croissant on a ceramic plate",
    tags: ["croissant", "almond", "pastry"],
    popular: true,
  },
  {
    id: "cinnamon-roll",
    name: "Cinnamon Roll",
    detail: "Soft brioche roll, cinnamon sugar, glaze",
    category: "Bakery",
    priceCents: 48000,
    image: "/menu/cinnamon-roll.jpg",
    imageAlt: "A glazed cinnamon roll on a ceramic plate",
    tags: ["cinnamon", "roll", "pastry"],
  },
  {
    id: "blueberry-muffin",
    name: "Blueberry Muffin",
    detail: "Golden muffin, blueberries, vanilla crumb",
    category: "Bakery",
    priceCents: 42000,
    image: "/menu/blueberry-muffin.jpg",
    imageAlt: "A blueberry muffin on a ceramic plate",
    tags: ["muffin", "blueberry", "cake"],
  },
  {
    id: "tiramisu-cup",
    name: "Tiramisu Cup",
    detail: "Mascarpone, espresso sponge, cocoa",
    category: "Dessert",
    priceCents: 69000,
    image: "/menu/tiramisu-cup.jpg",
    imageAlt: "A tiramisu cup dessert with cocoa",
    tags: ["tiramisu", "dessert", "espresso"],
  },
];

export function formatVnd(cents: number) {
  return new Intl.NumberFormat("vi-VN", {
    style: "currency",
    currency: "VND",
    maximumFractionDigits: 0,
  }).format(cents);
}

export function getProduct(productId: string) {
  return catalog.find((item) => item.id === productId);
}
